### ISSUE TITLE
Cannot find exercises on Windows with rustlings run

### ISSUE THREAD

**Issue by sebsebmc** [rust-lang/rustlings#138]
When trying to use `rustlings run` in order to check a single exercise I always get the error `No exercise found for your filename!`

I have tried many different combinations of leading `./`, `/` vs `\` and with or without the file extension and I was not able to get an exercise to run.

**Comment by charlie632** [comment]
Having the same issue

**Comment by komaeda** [comment]
This might be fixed by #143?

**Comment by komaeda** [comment]
Assuming this is fixed by #143. If not, please comment and I'll reopen!

**Comment by FedeCuci** [comment]
I got this exact error on Linux. I am using the following command from the `/rustlings` directory:
`rustlings run exercises/primitive_types/primitive_types2.rs`
This produced the following error:
`No exercise found for your given name!`
I have tried supplying the absolute path as well, but still get the same error.

**Comment by vishal590** [comment]
$ rustlings watch
C:\Users\hp\.cargo\bin\rustlings.exe must be run from the rustlings directory
Try `cd rustlings/`!
getting this error
this is current path -  /f/rust-p/rustlings/exercises/primitive_types ((4.6.0))

**Comment by diannasoreil** [comment]
> this is current path - /f/rust-p/rustlings/exercises/primitive_types ((4.6.0))

Try running `rustlings watch` from the `/f/rust-p/rustlings` directory.
